/**
 * c08-game-list — Game catalog screen with GameType + provider filters and a 3-col grid.
 *
 * Generated by ui-from-references skill (Phase 3 — CODE).
 * Tokens: ../design-tokens.json (v0.1.0)
 * Assets: ../asset-manifest.json (v0.1.0)
 * Reference: ../../../bake-off/client-flows/c08-game-list.png
 *
 * Anti-patterns to AVOID in this file:
 *  - inline hex codes (use Tailwind token classes)
 *  - emoji icons (use Lucide)
 *  - arbitrary Tailwind values (no bg-[#xxx])
 *  - default Tailwind colors (gray-500, blue-500, etc.)
 */
import { ChevronLeft, LayoutGrid, Search } from "lucide-react";

import { BottomNav } from "../components/bottom-nav";
import { Chip } from "../components/chip";

import bigBassBonanza from "../public/assets/game/big-bass-bonanza.png";
import caishenWins from "../public/assets/game/caishen-wins.png";
import fortuneTiger from "../public/assets/game/fortune-tiger.png";
import luckyNeko from "../public/assets/game/lucky-neko.png";
import mahjongWays from "../public/assets/game/mahjong-ways.png";
import starlightPrincess from "../public/assets/game/starlight-princess.png";
import sweetBonanza from "../public/assets/game/sweet-bonanza.png";
import treasuresOfAztec from "../public/assets/game/treasures-of-aztec.png";
import wildWestGold from "../public/assets/game/wild-west-gold.png";

type Badge = "NEW" | "HOT" | null;

type Game = {
  id: string;
  name: string;
  provider: string;
  image: string;
  badge?: Badge;
};

const GAMES: Game[] = [
  { id: "mahjong-ways",       name: "Mahjong Ways",       provider: "PG Soft",   image: mahjongWays,       badge: "HOT" },
  { id: "lucky-neko",         name: "Lucky Neko",         provider: "PG Soft",   image: luckyNeko,         badge: "NEW" },
  { id: "sweet-bonanza",      name: "Sweet Bonanza",      provider: "Pragmatic", image: sweetBonanza,      badge: "HOT" },
  { id: "wild-west-gold",     name: "Wild West Gold",     provider: "Pragmatic", image: wildWestGold,      badge: null },
  { id: "treasures-of-aztec", name: "Treasures of Aztec", provider: "PG Soft",   image: treasuresOfAztec,  badge: null },
  { id: "caishen-wins",       name: "Caishen Wins",       provider: "PG Soft",   image: caishenWins,       badge: "NEW" },
  { id: "big-bass-bonanza",   name: "Big Bass Bonanza",   provider: "Pragmatic", image: bigBassBonanza,    badge: null },
  { id: "fortune-tiger",      name: "Fortune Tiger",      provider: "PG Soft",   image: fortuneTiger,      badge: "HOT" },
  { id: "starlight-princess", name: "Starlight Princess", provider: "Pragmatic", image: starlightPrincess, badge: null },
];

const GAME_TYPES = ["สล็อต", "คาสิโนสด", "โป๊กเกอร์", "กีฬา", "ยิงปลา"] as const;
const PROVIDERS = ["ทั้งหมด", "PG Soft", "Pragmatic", "Evolution", "Joker"] as const;

export default function GameListScreen() {
  return (
    <div className="min-h-screen max-w-[440px] mx-auto bg-bg-base text-text-primary font-body pb-22">
      <StatusBar />
      <Header />
      <GameTypeFilter active="สล็อต" />
      <ProviderFilter active="ทั้งหมด" />
      <p className="px-4 pt-2 pb-1 text-caption text-text-secondary">พบ 247 เกม</p>
      <GameGrid games={GAMES} />
      <LoadMore />
      <BottomNav active="none" />
    </div>
  );
}

function StatusBar() {
  return (
    <div className="h-13 px-7 flex items-center justify-between text-caption font-bold">
      <span>9:41</span>
      <div className="w-28 h-7 rounded-full bg-black" aria-hidden="true" />
      <span className="text-text-primary">●●●</span>
    </div>
  );
}

function Header() {
  return (
    <header className="h-13 px-4 flex items-center justify-between">
      <button type="button" aria-label="ย้อนกลับ" className="text-text-primary">
        <ChevronLeft className="size-6" strokeWidth={2} aria-hidden="true" />
      </button>
      <h1 className="text-title font-bold">เกมทั้งหมด</h1>
      <div className="flex items-center gap-4 text-text-primary">
        <button type="button" aria-label="ค้นหา">
          <Search className="size-5" strokeWidth={2} aria-hidden="true" />
        </button>
        <button type="button" aria-label="สลับมุมมอง">
          <LayoutGrid className="size-5" strokeWidth={2} aria-hidden="true" />
        </button>
      </div>
    </header>
  );
}

function GameTypeFilter({ active }: { active: (typeof GAME_TYPES)[number] }) {
  return (
    <div className="px-4 py-2 flex gap-2 overflow-x-auto">
      {GAME_TYPES.map((t) => (
        <Chip key={t} active={t === active}>{t}</Chip>
      ))}
    </div>
  );
}

function ProviderFilter({ active }: { active: (typeof PROVIDERS)[number] }) {
  return (
    <div className="px-4 py-1 flex gap-2 overflow-x-auto">
      {PROVIDERS.map((p) => (
        <Chip key={p} active={p === active} size="sm">{p}</Chip>
      ))}
    </div>
  );
}

function GameGrid({ games }: { games: Game[] }) {
  return (
    <ul className="px-4 grid grid-cols-3 gap-1.5">
      {games.map((g) => (
        <li key={g.id}>
          <GameTile game={g} />
        </li>
      ))}
    </ul>
  );
}

function GameTile({ game }: { game: Game }) {
  return (
    <article className="relative rounded-md overflow-hidden bg-bg-raised border border-border-subtle">
      <img
        src={typeof game.image === "string" ? game.image : (game.image as unknown as { src: string }).src}
        alt={game.name}
        className="aspect-[4/3] w-full object-cover"
      />
      {game.badge && (
        <span
          className={`absolute top-1.5 right-1.5 rounded-sm px-1.5 py-0.5 text-micro font-bold text-text-inverse ${
            game.badge === "NEW" ? "bg-accent-primary" : "bg-accent-warning"
          }`}
        >
          {game.badge === "NEW" ? "ใหม่" : "ฮอต"}
        </span>
      )}
      <div className="p-2 flex flex-col gap-0.5">
        <span className="text-caption font-bold text-text-primary truncate">{game.name}</span>
        <span className="text-micro text-text-secondary truncate">{game.provider}</span>
      </div>
    </article>
  );
}

function LoadMore() {
  return (
    <div className="py-4 flex justify-center">
      <button
        type="button"
        className="h-10 px-6 rounded-pill bg-bg-raised border border-border-subtle text-body font-bold text-text-primary"
      >
        โหลดเพิ่ม
      </button>
    </div>
  );
}
