/**
 * c16-deposit-landing — Deposit method picker with balance, active promo, and 4 payment methods.
 *
 * Generated by ui-from-references skill (Phase 3 — CODE).
 * Tokens: ../design-tokens.json (v0.1.0)
 * Assets: ../asset-manifest.json (v0.1.0)
 * Reference: ../../../bake-off/client-flows/c16-deposit-landing.png
 *
 * Anti-patterns to AVOID in this file:
 *  - inline hex codes (use Tailwind token classes)
 *  - emoji icons (use Lucide)
 *  - arbitrary Tailwind values (no bg-[#xxx])
 *  - default Tailwind colors (gray-500, blue-500, etc.)
 */
import { AlertTriangle, ChevronRight, Coins, Gift, Landmark, QrCode, Wallet, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";

import { BottomNav } from "../components/bottom-nav";

type PaymentMethod = {
  id: string;
  icon: LucideIcon;
  iconTone: "primary" | "warning" | "accent";
  title: string;
  subtitle: string;
};

const METHODS: PaymentMethod[] = [
  { id: "promptpay", icon: QrCode,   iconTone: "primary", title: "พร้อมเพย์ / สแกน QR",   subtitle: "ฝากขั้นต่ำ ฿100" },
  { id: "truemoney", icon: Wallet,   iconTone: "warning", title: "ทรูมันนี่ วอลเล็ท",      subtitle: "ฝากขั้นต่ำ ฿50"  },
  { id: "bank",      icon: Landmark, iconTone: "accent",  title: "โอนเข้าบัญชีธนาคาร", subtitle: "ฝากขั้นต่ำ ฿300" },
  { id: "usdt",      icon: Coins,    iconTone: "primary", title: "USDT (TRC20)",            subtitle: "ฝากขั้นต่ำ ฿200" },
];

const ICON_TONE: Record<PaymentMethod["iconTone"], string> = {
  primary: "text-accent-primary",
  warning: "text-accent-warning",
  accent: "text-text-primary",
};

export default function DepositLandingScreen() {
  return (
    <div className="min-h-screen max-w-[440px] mx-auto bg-bg-base text-text-primary font-body pb-22">
      <StatusBar />
      <Header />
      <div className="px-4 pt-2 flex flex-col gap-4">
        <BalanceCard />
        <PromoBanner />
        <h2 className="text-heading font-bold pt-2">เลือกช่องทางการฝาก</h2>
        <ul className="flex flex-col gap-2.5">
          {METHODS.map((m) => (
            <li key={m.id}>
              <PaymentMethodCard method={m} />
            </li>
          ))}
        </ul>
        <Notice />
      </div>
      <BottomNav active="wallet" />
    </div>
  );
}

function StatusBar() {
  return (
    <div className="h-13 px-7 flex items-center justify-between text-caption font-bold">
      <span>9:41</span>
      <div className="w-28 h-7 rounded-full bg-black" aria-hidden="true" />
      <span className="text-text-primary">●●●</span>
    </div>
  );
}

function Header() {
  return (
    <header className="h-13 px-4 flex items-center justify-between relative">
      <span className="w-6" aria-hidden="true" />
      <h1 className="absolute inset-x-0 mx-auto w-fit text-title font-bold">ฝากเงิน</h1>
      <button type="button" aria-label="ปิด" className="text-text-primary">
        <X className="size-6" strokeWidth={2} aria-hidden="true" />
      </button>
    </header>
  );
}

function BalanceCard() {
  return (
    <section className="rounded-card bg-bg-raised border border-border-subtle p-5 flex flex-col gap-1">
      <span className="text-caption text-text-secondary">ยอดเงินปัจจุบัน</span>
      <span className="text-display font-display font-bold leading-display tracking-tight">฿ 1,250.00</span>
      <span className="flex items-center gap-1.5 text-caption text-text-secondary">
        <Coins className="size-4" strokeWidth={2} aria-hidden="true" />
        เงินโบนัส ฿0.00
      </span>
    </section>
  );
}

function PromoBanner() {
  return (
    <section className="rounded-card bg-bg-raised border border-accent-primary p-4 flex flex-col gap-1">
      <span className="flex items-center gap-2 text-body font-bold text-text-primary">
        <Gift className="size-5 text-accent-primary" strokeWidth={2.25} aria-hidden="true" />
        โบนัส 100% สำหรับการฝากครั้งนี้
      </span>
      <span className="text-caption text-text-secondary">สูงสุด ฿5,000 — เทิร์น x10</span>
      <button type="button" className="self-end text-caption font-bold text-accent-primary">
        เปลี่ยนโปรโมชั่น →
      </button>
    </section>
  );
}

function PaymentMethodCard({ method }: { method: PaymentMethod }) {
  const Icon = method.icon;
  return (
    <button
      type="button"
      className="w-full rounded-md bg-bg-raised border border-border-subtle p-4 flex items-center gap-3 text-start"
    >
      <Icon className={`size-6 shrink-0 ${ICON_TONE[method.iconTone]}`} strokeWidth={2} aria-hidden="true" />
      <span className="flex-1 flex flex-col gap-0.5">
        <span className="text-body text-text-primary">{method.title}</span>
        <span className="text-caption text-text-secondary">{method.subtitle}</span>
      </span>
      <ChevronRight className="size-5 text-text-secondary shrink-0" strokeWidth={2} aria-hidden="true" />
    </button>
  );
}

function Notice() {
  return (
    <p className="flex items-start gap-2 text-caption text-accent-warning">
      <AlertTriangle className="size-4 shrink-0 mt-0.5" strokeWidth={2.25} aria-hidden="true" />
      ห้ามใช้ชื่อบัญชีคนอื่นในการโอนเงิน
    </p>
  );
}
